server:
  port: 8040

logging:
  file: logs/devcode.log

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  thymeleaf:
      prefix: classpath:/templates/
      cache: false
